#interupting normal flow of a code
#we can handle error by error handling

'''

a=10

try:
    print(a)
except:
    print("error")
else:
    print("no error")
finally:
    print("always")


'''

a=10

try:
    print(b)
except:
    print("error")
else:
    print("no error")
finally:
    print("always")


